spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
               name: department-service
               fallbackuri: forward:/deartmentfallback  
           
server:  port: 8800            
            
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000       
        
         
       

           